# Generated by Django 5.1.7 on 2026-03-16 04:27

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0002_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historia_clinica",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "db_table": "historias_clinicas",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("motivo_consulta", models.TextField()),
                ("examen_fisico", models.JSONField(default=dict)),
                ("plan_terapeutico", models.TextField(blank=True, default="")),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("virtual", "Virtual")],
                        default="presencial",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cita",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consulta",
                        to="agenda.cita",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="agenda.tipoconsulta",
                    ),
                ),
                (
                    "hce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="hce.historiaclinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "db_table": "consultas",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="MedicamentoPrescrito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("presentacion", models.CharField(max_length=100)),
                ("dosis", models.CharField(max_length=100)),
                ("frecuencia", models.CharField(max_length=100)),
                ("duracion", models.CharField(max_length=100)),
                ("indicaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos",
                        to="hce.consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento Prescrito",
                "verbose_name_plural": "Medicamentos Prescritos",
                "db_table": "medicamentos_prescritos",
            },
        ),
        migrations.CreateModel(
            name="SignosVitales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "talla_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "imc",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.ExpressionWrapper(
                            django.db.models.expressions.CombinedExpression(
                                models.F("peso_kg"),
                                "/",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("talla_cm"), "/", models.Value(100.0)
                                    ),
                                    "*",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("talla_cm"), "/", models.Value(100.0)
                                    ),
                                ),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=2, max_digits=5
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=5, null=True
                        ),
                    ),
                ),
                ("pa_sistolica", models.SmallIntegerField(blank=True, null=True)),
                ("pa_diastolica", models.SmallIntegerField(blank=True, null=True)),
                ("fc", models.SmallIntegerField(blank=True, null=True)),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("saturacion_o2", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signos_vitales",
                        to="hce.consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signos Vitales",
                "verbose_name_plural": "Signos Vitales",
                "db_table": "signos_vitales",
            },
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["hce", "-fecha_hora"], name="consultas_hce_id_743113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["deleted_at"], name="consultas_deleted_395b53_idx"
            ),
        ),
    ]
