# Generated by Django 5.1.7 on 2026-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hce", "0002_add_diagnostico_consulta"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="diagnosticoconsulta",
            new_name="diagnostico_codigo__800034_idx",
            old_name="diagnosticos_cie10_idx",
        ),
        migrations.RenameIndex(
            model_name="diagnosticoconsulta",
            new_name="diagnostico_consult_8e4a0f_idx",
            old_name="diagnosticos_consulta_tipo_idx",
        ),
    ]
