# Generated by Django 5.1.7 on 2026-03-16 04:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("telefono_whatsapp", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacientes",
                        to="authentication.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "pacientes",
                "ordering": ["apellido", "nombre"],
                "indexes": [
                    models.Index(fields=["cedula"], name="pacientes_cedula_bddcda_idx"),
                    models.Index(
                        fields=["apellido", "nombre"],
                        name="pacientes_apellid_f523df_idx",
                    ),
                    models.Index(
                        fields=["deleted_at"], name="pacientes_deleted_122689_idx"
                    ),
                ],
            },
        ),
    ]
