# Generated by Django 5.1.7 on 2026-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_add_factura_performance_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="factura",
            name="factura_sede_fecha_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="facturas_sede_id_5c07f4_idx",
            old_name="facturas_sede_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="facturas_pacient_809fa9_idx",
            old_name="facturas_paciente_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="facturas_estado_a2212f_idx",
            old_name="facturas_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="factura",
            new_name="facturas_deleted_abc63b_idx",
            old_name="facturas_deleted_at_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientoinventario",
            new_name="movimientos_inventa_2b29bb_idx",
            old_name="movimientos_inv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="pago",
            new_name="pagos_factura_4e3a1b_idx",
            old_name="pagos_factura_idx",
        ),
        migrations.RenameIndex(
            model_name="pago",
            new_name="pagos_fecha_p_8536b9_idx",
            old_name="pagos_fecha_pago_idx",
        ),
    ]
