# Generated by Django 5.1.7 on 2026-03-16 04:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                ("duracion_min", models.PositiveSmallIntegerField()),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("virtual", "Virtual")],
                        default="presencial",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas_previas", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "db_table": "citas",
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="TipoConsulta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("duracion_min", models.PositiveSmallIntegerField()),
                ("tarifa_rd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("color_hex", models.CharField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Consulta",
                "verbose_name_plural": "Tipos de Consulta",
                "db_table": "tipos_consulta",
                "ordering": ["nombre"],
            },
        ),
    ]
