# Generated by Django 5.1.7 on 2026-03-16 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("authentication", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="profesional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="sede",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="authentication.sede",
            ),
        ),
        migrations.AddField(
            model_name="cita",
            name="tipo_consulta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="agenda.tipoconsulta",
            ),
        ),
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(
                fields=["fecha_hora", "sede"], name="citas_fecha_h_373851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(
                fields=["profesional", "fecha_hora"], name="citas_profesi_45464b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(fields=["deleted_at"], name="citas_deleted_696dbe_idx"),
        ),
    ]
