# Generated by Django 5.1.7 on 2026-03-17 02:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recordatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                        max_length=20,
                    ),
                ),
                ("anticipacion_horas", models.PositiveSmallIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Enviado"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("enviado_at", models.DateTimeField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordatorios",
                        to="agenda.cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio",
                "verbose_name_plural": "Recordatorios",
                "db_table": "recordatorios",
                "indexes": [
                    models.Index(
                        fields=["cita", "canal", "anticipacion_horas"],
                        name="recordatori_cita_id_5cc905_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="recordatori_estado_89e682_idx"
                    ),
                ],
            },
        ),
    ]
