# Generated by Django 5.1.7 on 2026-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_add_cita_performance_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cita",
            name="cita_sede_fecha_estado_idx",
        ),
    ]
