# Generated by Django 5.1.7 on 2026-03-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_auditlog_performance_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_table_ts_idx",
        ),
    ]
